"""
Document Models
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Enum, Text, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
from app.core.database import Base

class DocumentType(str, enum.Enum):
    """Document type"""
    CALCULATION_SHEET = "calculation_sheet"
    DESIGN_ASSESSMENT = "design_assessment"
    METHOD_STATEMENT = "method_statement"
    DPR = "dpr"  # Detailed Project Report
    COST_ESTIMATE = "cost_estimate"
    TENDER_DOCUMENT = "tender_document"
    BOQ = "boq"
    COMPLIANCE_REPORT = "compliance_report"
    AUDIT_REPORT = "audit_report"
    OTHER = "other"

class Document(Base):
    """Document model"""
    __tablename__ = "documents"
    
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    document_code = Column(String, unique=True, index=True, nullable=False)
    document_name = Column(String, nullable=False)
    document_type = Column(Enum(DocumentType), nullable=False)
    
    # File Information
    file_path = Column(String)  # Path to stored file
    file_name = Column(String)
    file_size = Column(Integer)  # in bytes
    mime_type = Column(String)
    
    # Content (for PDFs generated by system)
    content_data = Column(Text)  # JSON or structured data used to generate document
    
    # Version
    version = Column(Integer, default=1)
    is_latest = Column(Boolean, default=True)
    
    # Status
    is_approved = Column(Boolean, default=False)
    approved_by = Column(Integer, ForeignKey("users.id"))
    approved_at = Column(DateTime(timezone=True))
    
    # Metadata
    description = Column(Text)
    tags = Column(String)  # Comma-separated tags
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    project = relationship("Project", back_populates="documents")

class DocumentTemplate(Base):
    """Document Template"""
    __tablename__ = "document_templates"
    
    id = Column(Integer, primary_key=True, index=True)
    template_code = Column(String, unique=True, index=True, nullable=False)
    template_name = Column(String, nullable=False)
    document_type = Column(Enum(DocumentType), nullable=False)
    
    # Template Content
    template_content = Column(Text)  # Template structure/content
    template_format = Column(String)  # "pdf", "docx", "html"
    
    # Applicability
    applicable_project_types = Column(String)  # Comma-separated project types
    applicable_codes = Column(String)  # Comma-separated code standards
    
    # Status
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
